---
- name: Download installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /home/vagrant/composer-setup.php
    checksum: "sha384:48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5"
- name: Install
  become: true
  shell: php /home/vagrant/composer-setup.php --filename=composer --install-dir=/usr/local/bin

- name: Delete installer
  file: path=/home/vagrant/composer-setup.php state=absent
